# server setting
server:
  port: 8080

# spring setting
spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    show-sql: true
  data:
    mongodb:
#      host: localhost
#      port: 27017
#      database: danchu
      uri: mongodb://localhost:27017/danchu
  main:
    allow-bean-definition-overriding: true
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
